import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree, Outfit,Lavishly_Yours} from "next/font/google";
import "./globals.css";
import { ViewTransitions } from "next-view-transitions";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/Providers/theme-provider";
import { RootProvider } from 'fumadocs-ui/provider/next';

const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });
const outfit = Outfit({ subsets: ["latin"], variable: "--font-outfit" });
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lavishlyYours = Lavishly_Yours({ weight: "400", subsets: ["latin"], variable: "--font-lavishly-yours" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html
        lang="en"
        className={cn(
          "h-full",
          "antialiased",
          geistSans.variable,
          geistMono.variable,
          "font-sans",
          figtree.variable,
          outfit.variable,
          lavishlyYours.variable
        )}
      >
        <body className="min-h-full flex flex-col">
           <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
             <RootProvider>
                {children}
          </RootProvider>
          </ThemeProvider>
          </body>
      </html>
    </ViewTransitions>
  );
}
