const sharp = require("sharp");
const fs = require("fs");
const path = require("path");

const inputPath = path.join(__dirname, "../components/jackui/templates/ai-landing-page/public/Ai-landing-page01.png");
const outputPath = path.join(__dirname, "../components/jackui/templates/ai-landing-page/image-data.ts");

async function main() {
  try {
    console.log(`Reading source image from: ${inputPath}`);
    if (!fs.existsSync(inputPath)) {
      throw new Error(`Source image does not exist at ${inputPath}`);
    }

    const startSize = fs.statSync(inputPath).size;
    console.log(`Original size: ${(startSize / 1024 / 1024).toFixed(2)} MB`);

    // Compress to highly optimized WebP (resize to 1280px width to keep it small)
    console.log("Compressing image...");
    const webpBuffer = await sharp(inputPath)
      .resize({ width: 1280, withoutEnlargement: true })
      .webp({ quality: 70 })
      .toBuffer();

    console.log(`Compressed size: ${(webpBuffer.length / 1024).toFixed(2)} KB`);

    const base64String = webpBuffer.toString("base64");
    const dataUrl = `data:image/webp;base64,${base64String}`;

    // Write as a TS module
    const fileContent = `// This file is auto-generated by scripts/compress-image.js. Do not edit manually.
export const featureImg = "${dataUrl}";
`;

    fs.writeFileSync(outputPath, fileContent, "utf8");
    console.log(`Successfully generated Base64 image module at: ${outputPath}`);

  } catch (error) {
    console.error("Compression failed:", error);
    process.exit(1);
  }
}

main();
